# Generated by Django 5.2.4 on 2025-07-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patiant', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
