# Generated by Django 5.2.4 on 2025-07-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patiant', '0003_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_type',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='reason_for_visit',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_doctor',
        ),
    ]
