# Generated by Django 5.2.4 on 2025-07-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patiant', '0005_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
