# Generated by Django 5.2.4 on 2025-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patiant', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mobileno',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patiantname',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
