# Generated by Django 5.2.4 on 2025-08-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reception',
            new_name='Adminpanel',
        ),
    ]
