# Generated by Django 5.2.4 on 2025-07-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_register_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
