# Generated by Django 5.2.4 on 2025-07-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_register_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_register',
            new_name='main_user_register',
        ),
    ]
