# Generated by Django 5.2.4 on 2025-07-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_register_main_user_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main_user_register',
            new_name='User',
        ),
    ]
