# Generated by Django 5.2.4 on 2025-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_main_user_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmPassword',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
